### ISSUE TITLE
Flex Direction - Row Reverse

### ISSUE THREAD

**Issue by Senjo-code** [CodyHouse/cd-how-it-works-changelog#1]
Hello,

FYI - The css file contains the following code :

```
.hc4-grid {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
}
```

Display should be set to Flex, Grid prevents effects for the Flex Direction property.

Best Regards

**Comment by claudia-romano** [comment]
Hi there, where is row-reverse used? I double checked the component and I was not able to find any bugs. Thanks.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up! We have just pushed an updated version fixing the issue - we are using the `order` CSS property to control the position of text/images (rather than `flex-direction`).
